imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

twig:
    exception_controller: Behat\Borg\Integration\Symfony\Debug\Controller\ExceptionController::showAction

parameters:
    borg.cache_dir: %kernel.cache_dir%/build
    package.release_downloader.path: %borg.cache_dir%/releases
    documentation.build.path: %borg.cache_dir%/built_docs
    documentation.publisher.path: %borg.cache_dir%/published_docs
    extension.repo.path: %borg.cache_dir%/extensions
