homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    '::homepage.html.twig'
        section:     'homepage'

extension:
    resource: "@ExtensionBundle/Controller/"
    type:     annotation
    prefix:   /extensions
    defaults:
        section: 'extension'

documentation:
    resource: '@DocumentationBundle/Controller/'
    type:     annotation
    prefix:   /docs
    defaults:
        section: 'documentation'
    requirements:
        project: '[\w\-]++\/[\w\-]++'
        version: 'current|master|develop|v\d++\.\d++(?:\.x)?'
        path: '.*\.html'
